# Generated by Django 5.1.3 on 2025-02-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='first_prompt',
        ),
    ]
