# Generated by Django 5.1.1 on 2025-02-07 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0002_remove_chat_first_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('tool_responses', models.JSONField(blank=True, default=list, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_responses', to='chats_app.chat')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
