# Generated by Django 5.1.1 on 2025-02-09 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0003_llmresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='llmresponse',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='chat',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChatNotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.JSONField(default=list)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notes', to='chats_app.chat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
