# Generated by Django 5.1.1 on 2025-02-09 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0004_alter_chat_options_alter_llmresponse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnotes',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notes', to='chats_app.chat'),
        ),
    ]
