# Generated by Django 5.1.1 on 2025-02-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0005_alter_chatnotes_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnotes',
            name='notes',
            field=models.JSONField(default=dict),
        ),
    ]
