# Generated by Django 5.1.1 on 2025-02-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0008_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='attachments',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
