# Generated by Django 5.1.1 on 2025-02-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0009_chat_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='attachments',
        ),
        migrations.AddField(
            model_name='chat',
            name='img_attachment_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
